### ISSUE TITLE
设置页面上半部分显示异常

### ISSUE THREAD

**Issue by cheb2003** [x-hansong/CodeMaker#15]
在idea->settings->other settings->Code Maker显示如下界面，设置页面上半部分显示异常
idea2019.3

![TIM截图20191226111653](https://user-images.githubusercontent.com/3940902/71455719-45bec600-27d1-11ea-8e08-6042dfca4b13.png)

**Comment by x-hansong** [comment]
我这边是好的，你重装试一下
