### ISSUE TITLE
idea2021.2无法安装

### ISSUE THREAD

**Issue by oaichina** [x-hansong/CodeMaker#22]
![微信图片_20210810150450](https://user-images.githubusercontent.com/17543043/128823124-2bdc2106-07c7-451e-8d93-48a52915c6ea.png)
![微信图片_20210810150440](https://user-images.githubusercontent.com/17543043/128823153-c74b6369-5221-4b39-876d-ec7c3adb6f63.png)

**Comment by x-hansong** [comment]
![image](https://user-images.githubusercontent.com/5747697/128823371-21063a6b-ba63-4aa3-885b-e5597b817c24.png)
尝试从idea插件市场里面直接安装

**Comment by oaichina** [comment]
![image](https://user-images.githubusercontent.com/17543043/128823658-4c34072b-e293-4343-8687-0cbf3adcae97.png)
是在市场安装的。

**Comment by oaichina** [comment]
> ![image](https://user-images.githubusercontent.com/5747697/128823371-21063a6b-ba63-4aa3-885b-e5597b817c24.png)
> 尝试从idea插件市场里面直接安装
