### ISSUE TITLE
新建模板中含有中文会乱码？

### ISSUE THREAD

**Issue by wingslijun** [x-hansong/CodeMaker#3]
idea和项目都设置为utf-8，下载此插件在新建的vm文件中有中文，结果生成的文件中文都变乱码，是哪里设置的不对吗？

**Comment by x-hansong** [comment]
你是用windows进行开发吗？生成的代码文件默认是用系统的编码，window默认是GBK，所以会乱码。@wingslijun 下个版本我会提供自定义生成代码编码的选项。

**Comment by wingslijun** [comment]
OK 3Q
