### ISSUE TITLE
设置页打不开，Storage中的id属性没有了

### ISSUE THREAD

**Issue by gaifanking** [x-hansong/CodeMaker#9]
运行后，CodeMaker设置页一直loading，出不来设置页面。
怀疑跟{@Storage(id = "app-default", file = "$APP_CONFIG$/CodeMaker-settings.xml")}有关，新的SDK中已经去掉了id字段，但我删除id还是不好用，求解

**Comment by x-hansong** [comment]
try to reinstall the plugin.
